name: basp
description: "Assam Local Service App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core, Auth & Cloud Firestore Database
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.2

  # Passwordless Sign-In Providers
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1

  # UI Components & Maps
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.3

  # Live Assam Village & GPS Locator
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launch_background"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/
