name: basp
description: "Assam Local Service App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Auth
  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  google_sign_in: 6.1.6

  # UI Components & Maps
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launch_background"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
