name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Java 11 set kar rahe hain taaki purane Gradle versions ke sath Groovy error na aaye
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Assam-Local-Service-APK
          path: build/app/outputs/flutter-apk/app-release.apk
